baseURL = "https://justinmaccarthy.com/"
languageCode = "en-us"
title = "Justin's ployglot programming blog"
theme ="m10c"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3


[params]
    author = "Justin MacCarthy"
    description="Writing web projects since cgi.pm in 1995. It's been downhill from there for the web. Nothing lasts, and the tooling is insane."
    avatar= "https://avatars.githubusercontent.com/u/7726?v=4"
    menu_item_separator= "-"
    [[params.social]]
        icon = "github"
        name = "My Github"
        url = "https://github.com/macarthy"
    [[params.social]]
        icon = "twitter"
        name = "Twitter"
        url = "https://twitter.com/macarthy"
    [[params.social]]
        icon = "linkedin"
        name = "Linkedin"
        url = "https://www.linkedin.com/in/greatdeveloper"
    [[params.social]]
        icon = "mail"
        name = "Email"
        url = "mailto:justin@maccarthy.org"
